import NavBar from './components/NavBar'
import AuthContext from './context/AuthContext'
import './globals.css'
import "react-datepicker/dist/react-datepicker.css"
import { Inter, League_Spartan, Poppins } from 'next/font/google'
import Footer from './components/Footer'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

const league_spartan = League_Spartan({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-league-spartan'
})

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: '400'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable} ${league_spartan.variable} ${poppins.variable}`}>
      <head >
        <title>Rezos</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <main className="bg-white w-screen ">
        <AuthContext>
          <main className="max-w-screen-2xl m-auto bg-white">
            <NavBar />
            {children}
          </main>
        </AuthContext>          
        </main>    
        <Footer />
      </body>
    </html>
  )
}
